version: "3.9"

services:
  api:
    image: ghcr.io/teplovslava/balivito-backend-new:latest
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - uploads-data:/app/uploads 
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5

  libretranslate:
    image: libretranslate/libretranslate:latest  # стабильная версия
    restart: unless-stopped
    ports:
      - "5000:5000"


volumes:
  mongo-data:
  uploads-data:
