version: "3.9"

services:
  api:
    image: ghcr.io/teplovslava/<REPO>:latest   # собранный CI‑образ
    env_file: .env             # файл кладёт deploy‑job; на сервере рядом с compose
    ports:
      - "7777:7777"            # наружу доступен только API
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
