export const ERROR_MESSAGES = {
  chat_fetch_error: {
    en: "Failed to fetch chats",
    ru: "Ошибка при получении чатов",
    id: "Gagal mengambil chat",
    bjn: "Galak mangambil chat",
  },
  message_fetch_error: {
    en: "Failed to fetch messages",
    ru: "Ошибка при получении сообщений",
    id: "Gagal mengambil pesan",
    bjn: "Galak mangambil pesan",
  },
  invalid_reply_message: {
    en: "Invalid reply message",
    ru: "Некорректное сообщение для ответа",
    id: "Pesan balasan tidak valid",
    bjn: "Pesan balasan kada sah",
  },
  internal_server_error: {
    en: "Internal server error",
    ru: "Ошибка сервера",
    id: "Kesalahan server internal",
    bjn: "Kasalahan server",
  },
  file_not_uploaded: {
    en: "No files uploaded",
    ru: "Файлы не были загружены",
    id: "Tidak ada file diunggah",
    bjn: "Berataan kada diunggah",
  },
  file_not_found: {
    en: "File not found",
    ru: "Файл не найден",
    id: "File tidak ditemukan",
    bjn: "Berataan kada ditemukan",
  },
  no_access: {
    en: "No access",
    ru: "Нет доступа",
    id: "Tidak ada akses",
    bjn: "Kada kawa mambuka",
  },
  file_deleted: {
    en: "File deleted",
    ru: "Файл удалён",
    id: "File dihapus",
    bjn: "Berataan dihapus",
  },
  message_not_found: {
    en: "Message not found",
    ru: "Сообщение не найдено",
    id: "Pesan tidak ditemukan",
    bjn: "Pesan kada ditemukan",
  },
  cannot_react_self: {
    en: "Cannot react to your own message",
    ru: "Нельзя ставить реакцию на своё сообщение",
    id: "Tidak bisa memberi reaksi ke pesan sendiri",
    bjn: "Kada kawa mamberi reaksi pian punya pesan",
  },
  no_chat_access: {
    en: "No access to chat",
    ru: "Нет доступа к чату",
    id: "Tidak ada akses ke chat",
    bjn: "Kada kawa mambuka chat",
  },
  reaction_set_error: {
    en: "Failed to set reaction",
    ru: "Ошибка при установке реакции",
    id: "Gagal memberi reaksi",
    bjn: "Galak mamberi reaksi",
  },
  cannot_delete_message: {
    en: "You cannot delete this message",
    ru: "Вы не можете удалить это сообщение",
    id: "Anda tidak dapat menghapus pesan ini",
    bjn: "Pian kada kawa ngahapus pesan ini",
  },
  message_delete_error: {
    en: "Failed to delete message",
    ru: "Ошибка при удалении сообщения",
    id: "Gagal menghapus pesan",
    bjn: "Galak ngahapus pesan",
  },
  cannot_edit_message: {
    en: "You cannot edit this message",
    ru: "Вы не можете редактировать это сообщение",
    id: "Anda tidak dapat mengedit pesan ini",
    bjn: "Pian kada kawa ngedit pesan ini",
  },
  no_changes: {
    en: "No changes detected",
    ru: "Изменений не обнаружено",
    id: "Tidak ada perubahan",
    bjn: "Kada ada perubahan",
  },
  message_edit_error: {
    en: "Failed to edit message",
    ru: "Ошибка при редактировании сообщения",
    id: "Gagal mengedit pesan",
    bjn: "Galak ngedit pesan",
  },
  upload_error: {
    en: "Failed to upload images",
    ru: "Ошибка при загрузке изображений",
    id: "Gagal mengunggah gambar",
    bjn: "Galak mangunggah gambar",
  },
};
